version: '3'

services:
  arduino-security-system-postgres-db:
    build:
      dockerfile: Dockerfile
      context: database
    image: arduino-security-system-postgres-db
    container_name: arduino-security-system-postgres-db
    restart: always
    ports:
      - "5432:5432"
